### ISSUE TITLE
Application.environment(environment_id) fails with 404 HTTPError

### ISSUE THREAD

**Issue by dmitry-kiselev-light-it** [pmatias/python-acquia-cloud-2#18]
I'm trying to get an `Environment` object by environment id by calling Application.environment method, but it always raises HTTPError.

Steps to reproduce:
1. Get an Application object 
2. Get an Environment object by calling application.environment() method with valid environment id
3. Try to access the environment.data attribute or call some method of that instance

Example of the code I'm using which produces the error:
```
>>> client = AcquiaV2(api_key, api_secret) 
>>> application_filters = "name=@*{application_name}*" 
>>> application = client.applications(filters=application_filters).first() 
>>> environment_id = application.environments()["dev"]["id"] 
>>> environment = application.environment(environment_id) 
>>> environment.data 
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cloud.acquia.com/api/applications/{application_id}/{environment_id} 
```

Content of exception.response.json():
```
{'error': 'not_found', 'message': 'The path "api/applications/{application_id}/{environment_id}" does not match any known resources.'}
```

**Comment by pmatias** [comment]
Hey @dmitry-kiselev-light-it, what version of acapi2 are you using?

**Comment by pmatias** [comment]
I just double checked with the API docs (https://cloudapi-docs.acquia.com/#/Applications/getApplicationEnvironments) You shouldn't be able to call `application.environment(environment_id)`, so I'll either re-implement this method or completely remove it, to keep things simple and more in line with the documentation.

Instead, use `client.environment(environment_id)` which is the proper way to get information from the `/environments/` endpoint.
