### ISSUE TITLE
Add support for SSL management

### ISSUE THREAD

**Issue by jlfranklin** [pmatias/python-acquia-cloud-2#32]
The environment endpoints include support for managing SSL certificates. ([link](https://cloudapi-docs.acquia.com/#/); search for "ssl").

Please add some support for adding, removing, activating, and otherwise managing the SSL certificates in an environment.

**Comment by jlfranklin** [comment]
@pmatias, can you reopen this?

**Comment by pmatias** [comment]
Thanks for your contribution @jlfranklin ! I'm having a very hectic week but I'll get to this first thing on Monday
