### ISSUE TITLE
Stale bot makes community contributions difficult.

### ISSUE THREAD

**Issue by jlfranklin** [pmatias/python-acquia-cloud-2#36]
Stale bot keeps closing PRs, because they don't get attention in a timely manner.  The desire to keep a queue neat and clean by closing things that aren't moving is misguided when the maintainers and community don't work on open source projects on a daily basis, or when a particular project (like this one) isn't part of their routine.

Emails from Stale Bot are buried in other Github mail, and are often missed until well after Stale Bot has closed the PR.

Please turn off this feature.  It provides negative value to the project.

**Comment by pmatias** [comment]
You're absolutely right (and case in point), I'll try to tweak this a bit better (maybe remove it completely)

Sorry for the inconvenience :)
