### ISSUE TITLE
Environments filtering doesn't work correctly

### ISSUE THREAD

**Issue by darlev91** [pmatias/python-acquia-cloud-2#9]
We try to filter application's environments using Acquia API (by URL query param). 
URL looks like that:
```
https://cloud.acquia.com/api/applications/{applicationId}/environments?filters=name%3Dtest_env_name
```

But we get the full list of application's environments, not the specific one. 
The API docs are saying that we can filter them:
https://cloudapi-docs.acquia.com/#/Applications/getApplicationEnvironments

What could be a reason of it ?

**Comment by pmatias** [comment]
Thanks for reporting this @darlev91, my first guess is that this comes from Acquia, but I'll take a look as soon as I have some time.

**Comment by pmatias** [comment]
Hi @darlev91, I've just tried 

```
    apps = acquia.applications(filters="name=mysubscriptionname")
    app = apps.first().data
    print(app)
```

This worked fine for me on a specific subscription name. 

Can you try with that?

**Comment by darlev91** [comment]
Hi, @pmatias 
The problem is not in `applications` filtering, the problem is in `application.environments` filtering. 
I've just tried it and seems like nothing was changed.
I'm using next code to get Acquia client:
```
>>> from acapi2 import Acquia
>>> c = Acquia()
```
And next code line to get list of environments:
```
>>> envs = c.applications().first().environments()
```
It gives me the same result as next code line:
```
>>> filtered_envs = c.applications().first().environments(filters="name=dev")
```
But I think the last line of code should give info about only one environment.

**Comment by pmatias** [comment]
I see. Thanks for clarifying. I'll take a look again.

**Comment by pmatias** [comment]
I can confirm the filters are not working for this endpoint. I've raised the issue with Acquia. 

In the meantime

```
envs = c.applications().first().environments()
print(envs["dev"])
```

Should work as a workaround.

**Comment by NastHoloviz** [comment]
Hi @pmatias 
I found the reason of the issue: 
https://github.com/pmatias/python-acquia-cloud-2/blob/master/acapi2/resources/application.py#L60
Please update it to `"filter": filters,`

**Comment by pmatias** [comment]
Good eye @NastHoloviz!, I'll take a look later this week and add it for the next release.

**Comment by pmatias** [comment]
Will be out with 2.0.1
